"""Generate tokens.css (custom properties + Tailwind v4 @theme mapping) from tokens.json.

Run from the repo root:  python3 replica/design/build_tokens.py
Re-run after every change to tokens.json, then re-run contrast.py.
"""

import json
from pathlib import Path

HERE = Path(__file__).parent
with (HERE / "tokens.json").open(encoding="utf-8") as fh:
    t = json.load(fh)


def block(colors: dict, indent: str = "  ") -> str:
    return "\n".join(f"{indent}--hh-{k}: {v};" for k, v in colors.items())


type_lines = []
for name, s in t["type"].items():
    type_lines.append(f"  --text-{name}: {s['size'] / 16:g}rem;")
    type_lines.append(f"  --text-{name}--line-height: {s['line'] / s['size']:.3g};")
    type_lines.append(f"  --text-{name}--font-weight: {s['weight']};")

space = "\n".join(f"  --hh-space-{i}: {v / 16:g}rem;" for i, v in enumerate(t["space"]))
radius = "\n".join(f"  --radius-{k}: {v}px;" for k, v in t["radius"].items())
theme_colors = "\n".join(f"  --color-{k}: var(--hh-{k});" for k in t["color"])
bp = "\n".join(
    f"  --breakpoint-{k}: {v / 16:g}rem;" for k, v in t["layout"]["breakpoints"].items()
)

css = f"""/* Generated by replica/design/build_tokens.py from tokens.json. Do not edit by hand. */

/* 1. Runtime tokens: light on :root, dark via the OS setting or data-theme="dark". */
:root {{
{block(t["color"])}
  --hh-font-display: {t["font"]["display"]};
  --hh-font-sans: {t["font"]["sans"]};
  --hh-font-mono: {t["font"]["mono"]};
{space}
  --hh-shadow-card: {t["shadow"]["card"]};
  --hh-shadow-pop: {t["shadow"]["pop"]};
  --hh-motion-fast: {t["motion"]["fast"]};
  --hh-motion-base: {t["motion"]["base"]};
  --hh-ease: {t["motion"]["ease"]};
  --hh-content-max: {t["layout"]["content_max"]}px;
  --hh-booking-max: {t["layout"]["booking_max"]}px;
  --hh-sidebar: {t["layout"]["sidebar"]}px;
  --hh-header: {t["layout"]["header"]}px;
  --hh-tap: {t["layout"]["tap_target_min"]}px;
  color-scheme: light;
}}
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
{block(t["color_dark"], "    ")}
    color-scheme: dark;
  }}
}}
:root[data-theme="dark"] {{
{block(t["color_dark"])}
  color-scheme: dark;
}}
@media (prefers-reduced-motion: reduce) {{
  :root {{ --hh-motion-fast: 0ms; --hh-motion-base: 0ms; }}
}}

/* 2. Tailwind v4 mapping. Import this file after `@import "tailwindcss";`.
      Utilities read the runtime tokens, so bg-surface / text-muted switch with the theme. */
@theme inline {{
{theme_colors}
  --font-display: var(--hh-font-display);
  --font-sans: var(--hh-font-sans);
  --font-mono: var(--hh-font-mono);
{radius}
  --shadow-card: var(--hh-shadow-card);
  --shadow-pop: var(--hh-shadow-pop);
  --ease-hh: var(--hh-ease);
}}
@theme {{
{chr(10).join(type_lines)}
{bp}
}}
"""
(HERE / "tokens.css").write_text(css, encoding="utf-8")
print(
    f"wrote {HERE / 'tokens.css'}: {len(t['color'])} colours (light + dark), {len(t['type'])} type steps"
)
